name: Matrix

on: [push]

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 7, 8]
      # fail-fast: true
        # include:
        #   - os: ubuntu-latest
        #     node_version: 8
        #     is_ubuntu_8: "true"
        # exclude:
        #   - os: ubuntu-latest
        #     node_version: 6
        #   - os: ubuntu-latest
        #     node_version: 8

    runs-on: ${{ matrix.os }} # ubuntu-latest
    steps:
      - name: node-version
        run: |
          node -v
      - name: change-node-version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          # node-version: 6
      - name: node-version
        run: |
          node -v    